TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('relawan/', include('app4.urls')),
    path('listrelawan/', include('app5.urls')),
    path('donasibarang/', include('app3.urls')),
    path('donasiuang/', include('app2.urls')),
]

app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.home, name='home'),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'app2'

urlpatterns = [
    path('', views.FormPelanggan, name='fp'),
    path('/KonfirmasiPembayaran', views.KonfirmasiPembayaran, name='kp'),
    path('/KonfirmasiTerakhir', views.KonfirmasiTerakhir, name='kt'),
]

app2/models.py
from django.db import models

# Create your models here.
BANK = (
    ('', 'Pilih Bank'),
    ('Bank Mandiri', 'Bank Mandiri'),
    ('Bank BCA', 'Bank BCA'),
    ('Bank BNI', 'Bank BNI'),
    ('Bank BRI', 'Bank BRI'),
    ('Bank Niaga', 'Bank Niaga')
)

class Isi(models.Model):
    nama_orang = models.CharField(max_length = 100)
    nomor_hp = models.CharField(max_length = 100)
    alamat_email = models.CharField(max_length = 100)
    nama_bank = models.CharField(max_length = 100, choices=BANK)
    jumlah_donasi = models.CharField(max_length = 100)

app2/forms.py
from django import forms
from .models import Isi
from django.forms import ModelForm

class FormUtama(forms.ModelForm):
   

    class Meta:
        model = Isi
        nama_orang = forms.CharField(widget = forms.TextInput(attrs={
            "placeholder" : "Nama"
        }), label = "")

        nomor_hp = forms.CharField(widget = forms.TextInput(attrs={
            "placeholder" : "Nomor HP"
        }))

        jumlah_donasi = forms.CharField(widget = forms.TextInput(attrs={
            "placeholder" : "Jumlah Donasi"
        }))

        alamat_email = forms.EmailField()
        fields = "__all__"

app2/views.py
from django.shortcuts import render, redirect, reverse
from .models import Isi
from .forms import FormUtama
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def FormPelanggan(request):
    if request.method == "POST":
        form_utama = FormUtama(request.POST)
        context = {
        "formu" : form_utama
        }
        if form_utama.is_valid():
            form_utama.save()
            return render(request, 'KonfirmasiPembayaran.html', context)

    context = {
        "formu" : FormUtama(),
        "is_tambah_form" : True
    }
    return render(request, 'FormPelanggan.html', context)

def KonfirmasiPembayaran(request):
    if request.method == "POST":
        form_utama = FormUtama(request.POST)
        if form_utama.is_valid():
            form_utama.save()
        return redirect(reverse("app2:kt"))
        
def KonfirmasiTerakhir(request):
    return render(request, 'KonfirmasiTerakhir.html')

app2/templates/FormPelanggan.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .contentapp2{
            max-width: 500;
            background-color: gold;
            margin: auto;
            text-align:center;
        }
    </style>
</head>

<body style="background-color: orange;">
    {% include 'base.html' %}
    <div class="container" style="margin-top:50px; border: 3px solid black; background-color: cornsilk; width: 60%;">
        <div class="mt-5 d-flex justify-content-center align-items-center flex-column">
            <h2>Isi Form Donasi</h2>
            <br>
            <h3>Masukkan data diri</h3>
            <hr color="green">
            <form action="{% url 'app2:fp' %}" method="POST">
                {% csrf_token %}
                {{formu.nama_orang|as_crispy_field}}
                {{formu.nomor_hp|as_crispy_field}}
                {{formu.alamat_email|as_crispy_field}}
                <br>
                <h3>Metode pembayaran</h3>
                <hr color="green">
                {{formu.nama_bank|as_crispy_field}}
                <br>
                <h3>Jumlah donasi</h3>
                <hr color="green">
                {{formu.jumlah_donasi|as_crispy_field}}
                <input class="btn btn-primary" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</body>


{% endblock content %}

app2/templates/KonfirmasiPembayaran.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .contentapp2{
            background-color: rgb(250, 216, 173);
            max-width: 500;
            margin: auto;
            text-align:center;
        }
    </style>
</head>
<body style="background-color: orange;">
    {% include 'base.html' %}
    <div class="container" style="margin-top:50px; border: 3px solid black; background-color: cornsilk; width: 60%;">
        <div class="mt-5 d-flex justify-content-center align-items-center flex-column">
            <form action="{% url 'app2:kp' %}" method="POST">
                {% csrf_token %}
                <h2>KONFIRMASI PEMBAYARAN</h2>
                <br>
                <p><b>Jumlah Donasi:</b></p>
                <p style="color: green">Rp. {{formu.jumlah_donasi.data}}</p>
                <br>
                <p><b>Transfer ke:</b></p>
                <p style="color: grey;">464 464 464</p>
                <br>
                <p><b>Nama Bank:</b></p>
                <p>{{formu.nama_bank.data}}</p>
                <button type="submit" class="btn btn-primary">Confirm</button>
                <button class="btn btn-default" type="button">
                    <a href="{% url 'app2:fp' %}">Back</a>
                </button>
            </form>
        </div>   
    </div>
</body>

{% endblock content %}

app2/templates/KonfirmasiTerakhir.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .contentapp2{
            max-width: 500;
            background-color: gold;
            margin: auto;
            text-align:center;
        }
    </style>
</head>
<body style="background-color: orange;">
    {% include 'base.html' %}
    <div class="container" style="margin-top:50px; border: 3px solid black; background-color: cornsilk; width: 60%;">
        <div class="mt-5 d-flex justify-content-center align-items-center flex-column">
            <h2>PENGIRIMAN DONASI SUKSES!</h2>
            <br>
            <p>Uang donasi yang anda berikan telah kami terima.<br>
                Kami mengucapkan terima kasih atas bantuan yang diberikan</p>
            <a href="{% url 'app1:home' %}"><button class="btn btn-primary">Kembali ke Menu Utama</button></a>
        </div>
    </div>
    
</body>

{% endblock content %}