TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('relawan/', include('app4.urls')),
    path('listrelawan/', include('app5.urls')),
    path('donasibarang/', include('app3.urls')),
    path('donasiuang/', include('app2.urls')),
]

app5/urls.py
from django.urls import path

from .views import listrelawan
from .views import detailrelawan
from .views import deleterelawan

app_name = 'app5'

urlpatterns = [
    path('', listrelawan, name = 'listrelawan'),
    path('detailrelawan/<str:pk>', detailrelawan, name = 'readRelawan'),
    path('deleterelawan/<str:pk>/', deleterelawan, name = 'deleteRelawan')
]

app5/models.py
from django.db import models

# Create your models here.

app5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import sys, os
sys.path.append(os.path.abspath(os.path.join('..', 'app4')))

from app4.models import Relawan
# Create your views here.

def listrelawan(request):
    relawans = Relawan.objects.all()
    response = {}
    response['relawans'] = relawans

    return render(request, 'app5.html', response)

def detailrelawan(request, pk):
    relawans = Relawan.objects.get(id = pk)
    response = {'relawans' : relawans}
    return render(request, 'detailrelawan.html', response)

def deleterelawan(request, pk):
    relawans = Relawan.objects.get(id = pk)
    if request.method == "POST":
        relawans.delete()
        return HttpResponseRedirect('/listrelawan')
    response = {'relawans' : relawans}
    return render(request, 'deleterelawan.html', response)

app5/templates/app5.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html>
  {% block content %}
    <head>
        <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'style.css' %}">
          <title>
              List Relawan
          </title>
      </head>
      
      <body style="background-color:orange; font-family: Rubik;">
        {% include 'base.html' %}
        <div class = "container">
            <br>
            <div class="card" style="margin-top: 50px; margin-bottom: 50px;">
              <div class="card-header">
                List Relawan
              </div>
              <div class="card-body"> 
                {% if relawans %}
                <table class = "table table-sm">
                  <tr>
                    <th style="width:800px">Nama</th>
                    <th>View Detail</th>
                    <th>Remove</th>
                  </tr>
                  {% for relawan in relawans %}
                  <tr>
                    <td>{{ relawan.nama }}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'app5:readRelawan' relawan.id %}">View</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'app5:deleteRelawan' relawan.id %}">Remove</a></td>
                  </tr>
                  {% endfor %}
                </table>
                {% else %} 
                <p class="card-text">Belum ada relawan</p>
                {% endif %}
              </div>
          </div>
        </div>
        {% endblock content %}
        </body>
</html>

app5/templates/deleterelawan.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html>
  {% block content %}
    <head>
        <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'style.css' %}">
          <title>
              List Relawan
          </title>
      </head>
      
      <body style="background-color:orange; font-family: Rubik;">
        {% include 'base.html' %}
        <div class = "container">
            <br>
            <div class="card" style="margin-top: 50px; margin-bottom: 50px;">
              <div class="card-header">
                Delete Confirmation
              </div>
              <div class="card-body"> 
                <p class="card-text">Apakah anda yakin untuk mendelete relawan ini? </p>
                <form action = "{% url 'app5:deleteRelawan' relawans.id %}" method="POST">
                    {% csrf_token %}
                    <p class="card-text"><a class="btn btn-sm btn-info" href="{% url 'app5:listrelawan' %}">Cancel</a></p>
                    <input type="submit" class="btn btn-primary" name = "Confirm">
                </form>
              </div>
          </div>
        </div>
        {% endblock content %}
    </body>
</html>

app5/templates/detailrelawan.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html>
    {% block content %}
    <head>
        <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'style.css' %}">
          <title>
              List Relawan
          </title>
      </head>
      
      <body style="background-color:orange; font-family: Rubik;">
        {% include 'base.html' %}
        <div class = "container">
            <br>
            <div class="card" style="margin-top: 50px; margin-bottom: 50px;">
              <div class="card-header">
                <h5 class="card-title">{{ relawans.nama }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ relawans.nama_panggilan }}</h6>
              </div>
              <div class="card-body"> 
                <table class = "table table-sm">
                    <tr>
                      <th>No HP</th>
                      <td>: {{ relawans.no_hp }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>: {{ relawans.email }}</td>
                    </tr>
                    <tr>
                        <th>Identitas</th>
                        <td>: {{ relawans.identitas }}</td>
                    </tr>
                    <tr>
                        <th>No Identitas</th>
                        <td>: {{ relawans.no_identitas }}</td>
                    </tr>
                    <tr>
                        <th>Alamat</th>
                        <td>: {{ relawans.alamat }}</td>
                    </tr>
                    <tr>
                        <th>Jenis Kelamin</th>
                        <td>: {{ relawans.jenis_kelamin }}</td>
                    </tr>
                    <tr>
                        <th>Agama</th>
                        <td>: {{ relawans.agama }}</td>
                    </tr>
                    <tr>
                        <th>Status Perkawinan</th>
                        <td>: {{ relawans.status }}</td>
                    </tr>
                    <tr>
                        <th>Pekerjaan</th>
                        <td>: {{ relawans.pekerjaan }}</td>
                    </tr>
                    <tr>
                        <th>Perminatan Cluster</th>
                        <td>: {{ relawans.peminatan }}</td>
                    </tr>
              </div>
          </div>
        </div>
        {% endblock content %}
    </body>
</html>