TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('relawan/', include('app4.urls')),
    path('listrelawan/', include('app5.urls')),
    path('donasibarang/', include('app3.urls')),
    path('donasiuang/', include('app2.urls')),
]

app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.home, name='home'),
]

app3/urls.py
from django.urls import path

from . import views

app_name = 'app3'

urlpatterns = [
    path('', views.form_barang, name='form_barang'),
    path('success', views.success, name='success'),
    path('confirm', views.confirm, name='confirm')
]

app3/models.py
from django.db import models

# Create your models here.
BARANG = (
    ('', 'Choose...'),
    ('Pakaian', 'Pakaian'),
    ('Sembako', 'Sembako'),
    ('Lainnya', 'Lainnya')
)
class Barang(models.Model):
    nama_donatur = models.CharField(max_length=50)
    no_handphone = models.CharField(max_length=50)
    barang = models.CharField(max_length=50, choices=BARANG)
    date = models.DateField()
    place = models.CharField(max_length=50)

app3/forms.py
from django import forms
from .models import Barang
from django.forms import ModelForm
from tempus_dominus.widgets import DatePicker

class FormBarang(ModelForm):
    class Meta:
        model = Barang
        widgets = {
            'nama_donatur': forms.TextInput(attrs={'placeholder': 'Nama'}),
            'no_handphone': forms.TextInput(attrs={'placeholder': 'No handphone'}),
            'date' : forms.DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder' : 'dd/mm/yyyy',
                'type' : 'date',
                }),
            #'date' : DatePicker(),
            'place' : forms.TextInput(attrs={'placeholder': 'Alamat'}),

        }
        labels = {
            'date': 'Waktu penjemputan barang',
            'place': 'Alamat penjemputan barang',
        }
        # widgets = {
        #     'nama_donatur': forms.HiddenInput(),
        #     'no_handphone': forms.HiddenInput(),
        #     'date' : forms.HiddenInput(),
                
        #     # }, format='%d-%m-%Y %H:%M'
        #     #'date': forms.TextInput(attrs={'placeholder': 'Tanggal'}),
            
        #     'place' : forms.HiddenInput(),

        # }
        
        fields = '__all__'

    

app3/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import FormBarang


# Create your views here.
def form_barang(request):
    if(request.method == "POST"):
        form = FormBarang(request.POST)
        context = {'form' : form}
        if form.is_valid():
            #form.save()
            return render(request, 'app3/konfirmasi.html', context)
            
            #return HttpResponseRedirect('/donasibarang/success')
    else:
        form = FormBarang()
       
    context = {'form' : form}
    return render(request, "app3/donasibarang.html", context)

def success(request):
    return render(request, 'app3/sukses.html')

def confirm(request):
    if(request.method == "POST"):
        form=FormBarang(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/donasibarang/success')

app3/templates/app3/donasibarang.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
{% block content %}
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <title>Donasi Barang</title>
  {{ form.media }}
  <style>
    body{
      
    }
    .container{
      width: 60%;
      border: 3px solid orange;
      background-color: white;
      border-radius: 14px;
    }
  </style>
  </head>

<body style="background-color: green;">
  {% include 'base.html' %}
  <div class="container" style="margin-top: 50px; border: 3px solid orange; background-color: rgba(245, 245, 245, 0.9);">
    <h2 align="center" style="margin-top: 20px;">Isi Form Donasi</h2>
    <form action="{% url 'app3:form_barang' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" style="display: block; margin: 0 auto; margin-bottom: 50px; margin-top: 30px;">Confirm</button>
    </form>
  </div>
  
</body>
{% endblock content %}
</html>

app3/templates/app3/konfirmasi.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Konfirmasi Donasi Barang</title>
<style>
    .container{
      width: 60%;
      border-radius: 14px;
    }
</style>

</head>

<body style="background-color: green;">
  {% include 'base.html' %}
  <div  class="container" style="margin-top: 50px; border: 3px solid orange; background-color: rgba(245, 245, 245, 0.9);">
      <form action="{% url 'app3:confirm' %}" method="post">
        {% csrf_token %}
        {{form.nama_donatur.as_hidden}}
        {{form.no_handphone.as_hidden}}
        {{form.barang.as_hidden}}
        {{form.date.as_hidden}}
        {{form.place.as_hidden}}
        <h2 align="center">Konfirmasi</h2>
        <p><b>Nama donatur</b></p>
        <p>{{form.nama_donatur.data}}</p>
        <p><b>No handphone</b></p>
        <p>{{form.no_handphone.data}}</p>
        <p><b>Jenis Barang Yang Akan Disumbangkan</b></p>
        <p>{{form.barang.data}}</p>
        <p><b>Waktu Penjemputan Barang</b></p>
        <p>{{form.date.data}}</p>
        <p><b>Alamat Penjemputan Barang</b></p>
        <p>{{form.place.data}}</p>
        <button type="submit" class="btn btn-primary" style="display: block; margin: 0 auto;">Confirm</button><br>
        <button onclick="window.history.back();" class="btn btn-default" type="button" style="display: block; margin: 0 auto;">Back</button>
      </form>
  </div>
  
</body>
{% endblock content %}
</html>

app3/templates/app3/sukses.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Donasi Sukses</title>
<style>
    .container{
      width: 60%;
      border-radius: 14px;
    }
</style>

</head>

<body style="background-color: green;">
  {% include 'base.html' %}
  <div class="container" style="margin-top: 50px; border: 3px solid orange; background-color: rgba(245, 245, 245, 0.9);">
    <h2 align="center">Sukses</h2>
    <p align="center">Barang donasi yang anda berikan akan kami jemput.<br>Kami mengucapkan terimakasih atas bantuan yang anda berikan</p>
    <button type="button" class="btn btn-primary" style="display: block; margin: 0 auto;">
      <a style="text-decoration: none; color: white;" href="{% url 'app1:home' %}">Kembali ke menu utama</a>
    </button>
  </div>
</body>
{% endblock content %}
</html>