TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('relawan/', include('app4.urls')),
    path('listrelawan/', include('app5.urls')),
    path('donasibarang/', include('app3.urls')),
    path('donasiuang/', include('app2.urls')),
]

app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.home, name='home'),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'app2'

urlpatterns = [
    path('', views.FormPelanggan, name='fp'),
    path('/KonfirmasiPembayaran', views.KonfirmasiPembayaran, name='kp'),
    path('/KonfirmasiTerakhir', views.KonfirmasiTerakhir, name='kt'),
]

app3/urls.py
from django.urls import path

from . import views

app_name = 'app3'

urlpatterns = [
    path('', views.form_barang, name='form_barang'),
    path('success', views.success, name='success'),
    path('confirm', views.confirm, name='confirm')
]

app4/urls.py
from django.urls import path

from . import views

app_name = 'app4'

urlpatterns = [
    path('', views.relawan, name='relawan'),
    path('success/', views.success, name='success'),
]

templates/base.html
{% load static %}
{% url 'app1:home' as home_url %}
{% url 'app2:fp' as uang_url %}
{% url 'app3:form_barang' as barang_url %}
{% url 'app4:relawan' as relawan_url %}
{% url 'app5:listrelawan' as listrelawan_url %}

<!DOCTYPE html>
<html lang="en">
  {% block content %}
<head>
  {% block meta %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    

  {% endblock meta %}
</head>

<body>
  
 
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
    <a class="navbar-brand" href="#">ACT.ID</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item {%if request.path == home_url %} active {%endif%}">
          <a class="nav-link" href="{{home_url}}">Halaman Utama</a>
        </li>
        <li class="nav-item {%if request.path == uang_url %} active {%endif%}">
          <a class="nav-link" href="{{uang_url}}">Donasi Uang</a>
        </li>
        <li class="nav-item {%if request.path == barang_url %} active {%endif%}">
          <a class="nav-link" href="{{barang_url}}">Donasi Barang</a>
        </li>
        <li class="nav-item {%if request.path == relawan_url %} active {%endif%}">
          <a class="nav-link" href="{{relawan_url}}">Form Relawan</a>
        </li>
        <li class="nav-item  {%if request.path == listrelawan_url %} active {%endif%}">
          <a class="nav-link" href="{{listrelawan_url}}">List Relawan</a>
        </li>
        
      </ul>
    </div>
  </nav>
  

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
{% endblock content %}
</html>